
1) Fiquei um pouco confuso com o fato de precisar ser get => _privado ao invês de get;

2) Foi necessário utilizar de Console.WriteLine pois o throw new Exception aborta o programa;

3) ?